### ISSUE TITLE
Refrefrence to ab-mop, passing class names to find-method

### ISSUE THREAD

**Issue by Yehouda** [mnasoft/mnas-package#3]
https://github.com/mnasoft/mnas-package/blob/585188dfb3ffaf2b3466c76640f8741fa1b251c5/src/obj/obj-doc.lisp#L11

1) The code in this file refers to ab-mop, so doesn't work on other implemenations.
   Same as  [issue 7 in math](https://github.com/mnasoft/math/issues/7).
2) It passes class names as specializers to **find-method**, which is illegal .
   Same as [issue 10 in math](https://github.com/mnasoft/math/issues/10).

**Comment by mnasoft** [comment]
Thank you.
Corresponding changes have been made to the MNAS-PACKAGE system.
